//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSMQExplorer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MSMQExplorer.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files|*.*.
        /// </summary>
        internal static string AllFilesFilter {
            get {
                return ResourceManager.GetString("AllFilesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirrm Delete.
        /// </summary>
        internal static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to deleted the selected message?.
        /// </summary>
        internal static string ConfirmDeleteMessage {
            get {
                return ResourceManager.GetString("ConfirmDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Purge.
        /// </summary>
        internal static string ConfirmPurge {
            get {
                return ResourceManager.GetString("ConfirmPurge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to purge the selected queue? All messages will be deleted and cannot be recovered..
        /// </summary>
        internal static string ConfirmPurgeMessage {
            get {
                return ResourceManager.GetString("ConfirmPurgeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        internal static string ConfirmQueueDelete {
            get {
                return ResourceManager.GetString("ConfirmQueueDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected queue?.
        /// </summary>
        internal static string ConfirmQueueDeleteMessage {
            get {
                return ResourceManager.GetString("ConfirmQueueDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in DragDrop function.
        /// </summary>
        internal static string DragDropError {
            get {
                return ResourceManager.GetString("DragDropError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal Non-UI Error.
        /// </summary>
        internal static string Fatal_Non_UI_Error {
            get {
                return ResourceManager.GetString("Fatal_Non_UI_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal Non-UI Error.
        /// </summary>
        internal static string Fatal_Non_UI_Error_Detail {
            get {
                return ResourceManager.GetString("Fatal_Non_UI_Error_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal Windows Forms Error.
        /// </summary>
        internal static string Fatal_Windows_Forms_Error {
            get {
                return ResourceManager.GetString("Fatal_Windows_Forms_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing....
        /// </summary>
        internal static string FormMsmqExplorer_AddQueueNodeWithChildren_Processing___ {
            get {
                return ResourceManager.GetString("FormMsmqExplorer_AddQueueNodeWithChildren_Processing___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        internal static string FormMsmqExplorer_CreateQueue_Failed {
            get {
                return ResourceManager.GetString("FormMsmqExplorer_CreateQueue_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create the new queue:.
        /// </summary>
        internal static string FormMsmqExplorer_CreateQueue_Failed_to_create_the_new_queue_ {
            get {
                return ResourceManager.GetString("FormMsmqExplorer_CreateQueue_Failed_to_create_the_new_queue_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while attempting to delete the selected message:.
        /// </summary>
        internal static string FormMsmqExplorer_DeleteMessage_An_error_occurred_while_attempting_to_delete_the_selected_message_ {
            get {
                return ResourceManager.GetString("FormMsmqExplorer_DeleteMessage_An_error_occurred_while_attempting_to_delete_the_s" +
                        "elected_message_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message deleted from queue: .
        /// </summary>
        internal static string FormMsmqExplorer_DeleteMessage_Message_deleted_from_queue__ {
            get {
                return ResourceManager.GetString("FormMsmqExplorer_DeleteMessage_Message_deleted_from_queue__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete a system subqueue..
        /// </summary>
        internal static string FormMsmqExplorer_DeleteQueue_Cannot_delete_a_system_subqueue_ {
            get {
                return ResourceManager.GetString("FormMsmqExplorer_DeleteQueue_Cannot_delete_a_system_subqueue_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while formatting your XML. Please ensure it is valid..
        /// </summary>
        internal static string FormMsmqExplorer_FormatXml_An_error_has_occurred_while_formatting_your_XML__Please_ensure_it_is_valid_ {
            get {
                return ResourceManager.GetString("FormMsmqExplorer_FormatXml_An_error_has_occurred_while_formatting_your_XML__Pleas" +
                        "e_ensure_it_is_valid_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error formatting XML.
        /// </summary>
        internal static string FormMsmqExplorer_FormatXml_Error_formatting_XML {
            get {
                return ResourceManager.GetString("FormMsmqExplorer_FormatXml_Error_formatting_XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSMQ Explorer -  {0}.{1}.{2} Revision {3}.
        /// </summary>
        internal static string FormMsmqExplorer_InitMainWindow_MSMQ_Explorer_____0___1___2__Revision__3_ {
            get {
                return ResourceManager.GetString("FormMsmqExplorer_InitMainWindow_MSMQ_Explorer_____0___1___2__Revision__3_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while attempting to preview the selected message:.
        /// </summary>
        internal static string FormMsmqExplorer_PreviewMessage_An_error_occurred_while_attempting_to_preview_the_selected_message_ {
            get {
                return ResourceManager.GetString("FormMsmqExplorer_PreviewMessage_An_error_occurred_while_attempting_to_preview_the" +
                        "_selected_message_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previewed message from queue: .
        /// </summary>
        internal static string FormMsmqExplorer_PreviewMessage_Previewed_message_from_queue__ {
            get {
                return ResourceManager.GetString("FormMsmqExplorer_PreviewMessage_Previewed_message_from_queue__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  on host: .
        /// </summary>
        internal static string FormMsmqExplorer_PurgeQueue__on_host__ {
            get {
                return ResourceManager.GetString("FormMsmqExplorer_PurgeQueue__on_host__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purge.
        /// </summary>
        internal static string FormMsmqExplorer_PurgeQueue_Purge {
            get {
                return ResourceManager.GetString("FormMsmqExplorer_PurgeQueue_Purge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purged queue .
        /// </summary>
        internal static string FormMsmqExplorer_PurgeQueue_Purged_queue_ {
            get {
                return ResourceManager.GetString("FormMsmqExplorer_PurgeQueue_Purged_queue_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  from host: .
        /// </summary>
        internal static string FormMsmqExplorer_ReceiveMessage__from_host__ {
            get {
                return ResourceManager.GetString("FormMsmqExplorer_ReceiveMessage__from_host__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while receiving a message from the queue:.
        /// </summary>
        internal static string FormMsmqExplorer_ReceiveMessage_An_error_has_occurred_while_receiving_a_message_from_the_queue_ {
            get {
                return ResourceManager.GetString("FormMsmqExplorer_ReceiveMessage_An_error_has_occurred_while_receiving_a_message_f" +
                        "rom_the_queue_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message received on queue: .
        /// </summary>
        internal static string FormMsmqExplorer_ReceiveMessage_Message_received_on_queue__ {
            get {
                return ResourceManager.GetString("FormMsmqExplorer_ReceiveMessage_Message_received_on_queue__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while refreshing the queues from the specified host: .
        /// </summary>
        internal static string FormMsmqExplorer_RefreshRecControls_An_error_has_occurred_while_refreshing_the_queues_from_the_specified_host__ {
            get {
                return ResourceManager.GetString("FormMsmqExplorer_RefreshRecControls_An_error_has_occurred_while_refreshing_the_qu" +
                        "eues_from_the_specified_host__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect Error.
        /// </summary>
        internal static string FormMsmqExplorer_RefreshSendControls_Connect_Error {
            get {
                return ResourceManager.GetString("FormMsmqExplorer_RefreshSendControls_Connect_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  to host: .
        /// </summary>
        internal static string FormMsmqExplorer_SendMessage__to_host__ {
            get {
                return ResourceManager.GetString("FormMsmqExplorer_SendMessage__to_host__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred sending a message to the queue. If the XML box is checked, is your XML correctly formed?.
        /// </summary>
        internal static string FormMsmqExplorer_SendMessage_An_error_has_occurred_sending_a_message_to_the_queue__If_the_XML_box_is_checked__is_your_XML_correctly_formed_ {
            get {
                return ResourceManager.GetString("FormMsmqExplorer_SendMessage_An_error_has_occurred_sending_a_message_to_the_queue" +
                        "__If_the_XML_box_is_checked__is_your_XML_correctly_formed_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message sent on queue: .
        /// </summary>
        internal static string FormMsmqExplorer_SendMessage_Message_sent_on_queue__ {
            get {
                return ResourceManager.GetString("FormMsmqExplorer_SendMessage_Message_sent_on_queue__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter some message text to send!.
        /// </summary>
        internal static string FormMsmqExplorer_SendMessage_Please_enter_some_message_text_to_send_ {
            get {
                return ResourceManager.GetString("FormMsmqExplorer_SendMessage_Please_enter_some_message_text_to_send_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a queue!.
        /// </summary>
        internal static string FormMsmqExplorer_SendMessage_Please_select_a_queue_ {
            get {
                return ResourceManager.GetString("FormMsmqExplorer_SendMessage_Please_select_a_queue_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Error.
        /// </summary>
        internal static string FormMsmqExplorer_SendMessage_Send_Error {
            get {
                return ResourceManager.GetString("FormMsmqExplorer_SendMessage_Send_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host: .
        /// </summary>
        internal static string Host {
            get {
                return ResourceManager.GetString("Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In from Q:.
        /// </summary>
        internal static string MessageIn {
            get {
                return ResourceManager.GetString("MessageIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out to Q:.
        /// </summary>
        internal static string MessageOut {
            get {
                return ResourceManager.GetString("MessageOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSMQ Not Installed.
        /// </summary>
        internal static string MsmqNotInstalled {
            get {
                return ResourceManager.GetString("MsmqNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSMQ is not installed on this machine. In order for MSMQ Explorer to access MSMQ queues, it must be enabled on this machine. Do this via Control Panel &gt; Programs &gt; Turn Windows features on and off or via Server Manager. This application will now close..
        /// </summary>
        internal static string MsmqNotInstalledMessage {
            get {
                return ResourceManager.GetString("MsmqNotInstalledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Valid!.
        /// </summary>
        internal static string NotValid {
            get {
                return ResourceManager.GetString("NotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue: .
        /// </summary>
        internal static string Queue {
            get {
                return ResourceManager.GetString("Queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue Name.
        /// </summary>
        internal static string QueueName {
            get {
                return ResourceManager.GetString("QueueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive.
        /// </summary>
        internal static string Receive {
            get {
                return ResourceManager.GetString("Receive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        internal static string SaveAsOther {
            get {
                return ResourceManager.GetString("SaveAsOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as XML.
        /// </summary>
        internal static string SaveAsXml {
            get {
                return ResourceManager.GetString("SaveAsXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a file to open.
        /// </summary>
        internal static string SelectAllFile {
            get {
                return ResourceManager.GetString("SelectAllFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an XML file to open.
        /// </summary>
        internal static string SelectXml {
            get {
                return ResourceManager.GetString("SelectXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an XSD file to open.
        /// </summary>
        internal static string SelectXsd {
            get {
                return ResourceManager.GetString("SelectXsd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while creating the UI..
        /// </summary>
        internal static string UiError {
            get {
                return ResourceManager.GetString("UiError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid!.
        /// </summary>
        internal static string Valid {
            get {
                return ResourceManager.GetString("Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValidateXSD.
        /// </summary>
        internal static string ValidateXSD {
            get {
                return ResourceManager.GetString("ValidateXSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Files|*.xml.
        /// </summary>
        internal static string XmlFilter {
            get {
                return ResourceManager.GetString("XmlFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XSD Files|*.xsd.
        /// </summary>
        internal static string XsdFilter {
            get {
                return ResourceManager.GetString("XsdFilter", resourceCulture);
            }
        }
    }
}
